apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dahol/inventoryjs
    targetRevision: main
    path: frontend/app-config/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: inventoryjs-frontend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
