apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dahol/inventoryjsbackend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGUSER
              value: your_postgresql_username
            - name: PGHOST
              value: your_postgresql_host
            - name: PGDATABASE
              value: your_postgresql_database
            - name: PGPASSWORD
              value: your_postgresql_password
            - name: PGPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
