apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: inventoryjs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dahol/backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGUSER
              value: your_postgresql_username
            - name: PGHOST
              value: your_postgresql_host
            - name: PGDATABASE
              value: your_postgresql_database
            - name: PGPASSWORD
              value: your_postgresql_password
            - name: PGPORT
              value: "5432"
